[package]
name    = "diff_img"
version = "0.1.0"
edition = "2021"


[dependencies]
clap  = "4.5.16"
image = "0.25.5"
base64 = "0.9.0"
bytemuck = "1.16.0"
lcs-diff = "0.1.1"



[lib]
name = "diff_img"
path = "src/diff_img.rs"
